version: "3.9"

services:

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: quests
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d quests"]
      interval: 5s
      retries: 5
      start_period: 5s

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-dev
    environment:
      EULA: "true"
      TYPE: "PAPER"
      MEMORY: "2G"
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft/plugins:/data/plugins
      - ./minecraft/world:/data/world
      - ./minecraft/ops.json:/data/ops.json
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net

networks:
  net:
    driver: bridge
